---

name: Power-VPN
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          go-version: "^1.15.5"

      - uses: actions/checkout@v2.3.4

      - run: go get github.com/npxbr/verify-links/cmd/vl
      - run: vl -w thebloomapp.com,p3nlhclust404.shr.prod.phx3.secureserver.net,horde3d.org,puzzlescript.net,hacknplan.com,taiga.io,p1.untergrund.net README.md 
